name: Arch Linux User Repository (AUR) GitHub Action
description: Update package checksums or publish packages to the AUR.
author: JamieMagee
branding:
  icon: package
  color: blue

inputs:
  action:
    description: Which action to take. Can be 'updpkgsums' or 'publish'
    required: true
  pkgname:
    description: ""
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.action }}
    - ${{ inputs.pkgname }}
